version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tradesquash_dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5430:5430


volumes:
  db-data:
