name: Dialyzer

on: pull_request

jobs:
  check_dialyzer:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        elixir: ['1.14.4']
        otp: ['25']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        id: mix-dialyzer-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}, {1}', github.workspace, '/mix.lock'))}}

      - name: Install Mix Dependencies
        run: mix deps.get

      - name: Dialyzer
        run: mix dialyzer